[{"\u00e9quipe": "218", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 90, in <module>\n    affichage(executer(ARGS.debut, ARGS.fin), ARGS.debut, ARGS.fin, ARGS.valeur)\n  File \"projet1.py\", line 39, in executer\n    for key in changer_format(ARGS.symbole):\n  File \"projet1.py\", line 26, in changer_format\n    if datetime.date.today() - date_format(args1.debut) >= datetime.timedelta(100):\nNameError: name 'args1' is not defined\n</pre>\n"}, {"\u00e9quipe": "219", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> usage: projet1.py [-h] [-d DATE] [-f DATE] [-v TYPE]\nprojet1.py: error: unrecognized arguments: goog\n</pre>\n"}, {"\u00e9quipe": "221", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre>   File \"projet1.py\", line 35\n    cd C:\\Users\\Sarah\\Documents\\Ulaval\\7e session\\Python\\projet1\n       ^\nSyntaxError: invalid syntax\n</pre>\n"}, {"\u00e9quipe": "222", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> usage: projet1.py [-h] [-v TYPE] [-d DATE] [-f DATE] symbol\nprojet1.py: error: argument -d/--debut: invalid date value: '2018-09-21'\n</pre>\n"}, {"\u00e9quipe": "223", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 98, in <module>\n    main()\n  File \"projet1.py\", line 85, in main\n    for key in reversed(list(response['Time Series (Daily)'].keys())):\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "224", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 87, in <module>\n    print(sortiefinale(ARGS.valeur))\n  File \"projet1.py\", line 78, in sortiefinale\n    for key, value in sorted(RESPONSE['Time Series (Daily)'].items()):\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "225", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "226", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 134, in <module>\n    if RESPONSE['Time Series (Daily)'].get(LISTE_DATES_TIRETS[i]) is None:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "227", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"Projet1.py\", line 50, in <module>\n    if response['Time Series (Daily)'].get(str(date_0)) is None:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "228", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 69, in <module>\n    print(affichage(ARGS.symbole, ARGS.debut, ARGS.fin, ARGS.valeur))\n  File \"projet1.py\", line 66, in affichage\n    ligne2 = '{} \n {}'.format(ligne1, recevoirrequete(symbole, datedebut, datefin, valeur))\n  File \"projet1.py\", line 57, in recevoirrequete\n    liste = [(datedebut, response['Time Series (Daily)'][datedebut][valeur]),\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "229", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 171, in <module>\n    affichage(args.symbole, args.debut, args.fin, args.valeur)\n  File \"projet1.py\", line 166, in affichage\n    tuple_rep = (jour, reponse(jour, valeur, response))\n  File \"projet1.py\", line 151, in reponse\n    return response['Time Series (Daily)'][jour][dic_valeur[valeur]]\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "231", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> /home/pedro/.conda/envs/TA/bin/python: can't find '__main__' module in 'projet1.py'\n</pre>\n"}, {"\u00e9quipe": "232", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 69, in <module>\n    print(affichage(ARGS.symbole, ARGS.debut, ARGS.fin, ARGS.valeur))\n  File \"projet1.py\", line 66, in affichage\n    ligne2 = '{} \n {}'.format(ligne1, recevoirrequete(symbole, datedebut, datefin, valeur))\n  File \"projet1.py\", line 57, in recevoirrequete\n    liste = [(datedebut, response['Time Series (Daily)'][datedebut][valeur]),\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "234", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> usage: projet1.py [-h] [--symbole SYMBOLE] [-d DATE D\u00c9BUT DATE]\n                  [-f DATE FIN DATE]\n                  [-v {fermeture,ouverture,min,max,volume} VALEUR]\nprojet1.py: error: unrecognized arguments: -v=volume -d=2018-09-21 -f=2018-09-24 goog\n</pre>\n"}, {"\u00e9quipe": "235", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "236", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> usage: projet1.py [-h] [-v VALEUR]\nprojet1.py: error: unrecognized arguments: -d=2018-09-21 -f=2018-09-24 goog\n</pre>\n"}, {"\u00e9quipe": "237", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 133, in <module>\n    call_api(symbole)\n  File \"projet1.py\", line 113, in call_api\n    valeurs_associees = reponse_json['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "238", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 62, in <module>\n    if str(courante) in response[\"Time Series (Daily)\"]:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "240", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "242", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 108, in <module>\n    affichage(q, ARGS.v, ARGS.D, ARGS.F)\n  File \"projet1.py\", line 104, in affichage\n    print(jour(debut, fin, lecture(sorte), val))\n  File \"projet1.py\", line 75, in jour\n    liste_jour_dict = resp['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "243", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 12, in <module>\n    ARGS.dateFin, ARGS.valeur, ARGS.symbole)\n  File \"/mnt/Documents/Projets/Laval/TA/Partie4/unbundled/bundle-243-10.hg/info_bourse.py\", line 42, in get_infos\n    get_info(debut, fin, valeur, symbole)\n  File \"/mnt/Documents/Projets/Laval/TA/Partie4/unbundled/bundle-243-10.hg/info_bourse.py\", line 58, in get_info\n    resultat = [(debut_str, reponse['Time Series (Daily)'][debut_str][get_clee(valeur)])]\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "244", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 85, in <module>\n    valeuraction(DEBUT, FIN, SYMBOL)\n  File \"projet1.py\", line 64, in valeuraction\n    if str(une_date) in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "245", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "246", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 97, in <module>\n    premieredonnee = recuperer_compact()['Time Series (Daily)']['{}'.format(depart)][acess]\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "247", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: argument -d/--debut: invalid date value: '2018-09-21'\n</pre>\n"}, {"\u00e9quipe": "248", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 91, in <module>\n    main(args.DATE_DEBUT, args.DATE_FIN, args.VALUE, args.symbole)\n  File \"projet1.py\", line 88, in main\n    print(getActionValueWithDate(debut, fin, valeurConvertie, symbole))\n  File \"projet1.py\", line 60, in getActionValueWithDate\n    for dateElement in jsonResponse['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "250", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 100, in <module>\n    main(ARGS)\n  File \"projet1.py\", line 89, in main\n    for date_ in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "251", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "252", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 66, in <module>\n    formatfinal(ARGS.symbol)\n  File \"projet1.py\", line 63, in formatfinal\n    valeur_rechercher(liste[i])\n  File \"projet1.py\", line 52, in valeur_rechercher\n    d = response['Time Series (Daily)'][dd][val]\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "255", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 89, in <module>\n    dates_infos(premiere, deuxieme, response)\n  File \"projet1.py\", line 81, in dates_infos\n    if date in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}]