[{"\u00e9quipe": "087", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "111", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 127, in <module>\n    output_text()\n  File \"projet1.py\", line 100, in output_text\n    last = list(res['Time Series (Daily)'].keys())[-1].split('-')\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "067", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 50, in <module>\n    (args.date_debut, newResponse['Time Series (Daily)'][args.date_debut][value]),\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "068", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 126, in <module>\n    print(sortie_finale_programme())\n  File \"projet1.py\", line 122, in sortie_finale_programme\n    return resultat1(RESPONSE['Time Series (Daily)'], modification_date_debut(),\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "069", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 141, in <module>\n    print(affichage())\n  File \"projet1.py\", line 131, in affichage\n    return sortie1(response['Time Series (Daily)'], chaine_tansformation(),\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "070", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "071", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 90, in <module>\n    main()\n  File \"projet1.py\", line 87, in main\n    symbol.parse_values(api_helper.get(symbol_name, full_format))\n  File \"/mnt/Documents/Projets/Laval/TA/Partie2/unbundled/bundle-071-03.hg/api.py\", line 46, in get\n    \"Le symbole '{}' n'est surement pas valide.\".format(symbol)\nValueError: Une erreur s'est produite pendant la r\u00e9cup\u00e9ration des donn\u00e9es sur l'API. Le symbole 'goog' n'est surement pas valide.\n</pre>\n"}, {"\u00e9quipe": "072", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 86, in <module>\n    Projet1().action_jour()\n  File \"projet1.py\", line 79, in action_jour\n    if response['Time Series (Daily)'].get(str(instant.date())) is not None:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "073", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 89, in <module>\n    calcul_boursier(ARGS.symbole)\n  File \"projet1.py\", line 81, in calcul_boursier\n    if str(loopdate) in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "074", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 105, in <module>\n    fct_stock(ARGS.symbole)\n  File \"projet1.py\", line 98, in fct_stock\n    if i in response[\"Time Series (Daily)\"]:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "078", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "079", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "080", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "082", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "083", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 103, in <module>\n    finalpart1(ARGS.Symbole, ARGS.d, ARGS.f, ARGS.valeur)\n  File \"projet1.py\", line 69, in finalpart1\n    dico = get_data(symb[0])[\"Time Series (Daily)\"]\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "084", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "085", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"Projet1.py\", line 75, in <module>\n    fonction_principale()\n  File \"Projet1.py\", line 68, in fonction_principale\n    response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "086", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 111, in <module>\n    print(inf())\n  File \"projet1.py\", line 89, in inf\n    if str(datedebut) not in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "089", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "090", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "091", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 5, in <module>\n    parser.add_argument('symbole', dest='symb', nargs='+',type=list, help='Nom du symbole boursier d\u00e9sir\u00e9')\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1334, in add_argument\n    raise ValueError('dest supplied twice for positional argument')\nValueError: dest supplied twice for positional argument\n</pre>\n"}, {"\u00e9quipe": "092", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 94, in <module>\n    affichage(ARGS.symbole, '2018-09-24', '2018-10-01', ARGS.valeur)\n  File \"projet1.py\", line 86, in affichage\n    print('{}({}, {}, {})\n{}'.format(sym, val, deb, fi, extraction_des_valeurs(g\u00e9n\u00e9rateur_liste_jour('2018-09-24', '2018-10-01', catalogue_bourse(ARGS.symbole)), catalogue_bourse(ARGS.symbole))))\n  File \"projet1.py\", line 58, in g\u00e9n\u00e9rateur_liste_jour\n    for i in dico_bourse['Time Series (Daily)'].keys():\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "093", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 110, in <module>\n    retour.append(tuple(key_date, response[key_date][valeur]))\nKeyError: '2018-09-21'\n</pre>\n"}, {"\u00e9quipe": "094", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}, {"\u00e9quipe": "096", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 120, in <module>\n    print('{}\n{}'.format(LIGNE1, listeligne2(LISTE)))\n  File \"projet1.py\", line 113, in listeligne2\n    z = RESPONSE.get('Time Series (Daily)').get((str(a[i])))\nAttributeError: 'NoneType' object has no attribute 'get'\n</pre>\n"}, {"\u00e9quipe": "097", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 102, in <module>\n    CUT_RESPONSE = cut_info(INFORMATION, ARGS.debut, ARGS.fin, ARGS.valeur)\n  File \"projet1.py\", line 58, in cut_info\n    for jour in info[\"Time Series (Daily)\"].keys():\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "098", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 10, in <module>\n    description=\"Le programme courant affiche les valeurs de diff\u00e9rentes actions boursi\u00e8res.\")\nNameError: name 'ArgumentParser' is not defined\n</pre>\n"}, {"\u00e9quipe": "099", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 64, in <module>\n    dico = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "100", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "102", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "103", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 99, in <module>\n    tuplefinal(debut, fin, alpha_vantage(i))\n  File \"projet1.py\", line 89, in tuplefinal\n    if str(debut1) in response['Time Series (Daily)'].keys():\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "104", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"projet1.py\", line 80, in <module>\n    dico_dates = reponse['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "105", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Il n'y a pas de fichier projet1.py dans le dossier de votre bundle.</p>"}, {"\u00e9quipe": "106", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n<p>Votre erreur : <p>\n<pre> Traceback (most recent call last):\n  File \"PROJET1.py\", line 70, in <module>\n    print(affichage(ARGS.valeur, ARGS.debut, ARGS.fin, ARGS.symbole))\n  File \"PROJET1.py\", line 65, in affichage\n    ligne2 = '{}\n {}'.format(ligne1, fonction_1(valeur, debut, fin, symbole))\n  File \"PROJET1.py\", line 55, in fonction_1\n    sortie1 = (debut, response['Time Series (Daily)'][debut][valeur])\nKeyError: 'Time Series (Daily)'\n</pre>\n"}, {"\u00e9quipe": "113", "score": 0, "commentaires": "<h3>R\u00e9sultat crit\u00e8re 3</h3><p>Votre programme n'a pas fonctionn\u00e9 durant la correction...</p>\n<p>Un premier test (<code>[]</code>) a \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</p>\nIl y a peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionnement basique.</p>\n"}]