[{"critere": "1", "command": ["-h", "d\u00e9poser -h", "acheter -h", "vendre -h", "solde -h", "titres -h", "valeur -h", "projection -h"], "nom": "<p><h3>Commande Help", "erreurAttendu": [], "attendu": ["usage:"], "description": "<p><strong>V\u00e9rifier l'existence de la commande <code>help</code>.</strong></p>", "commentaire": "<p>La commande <code>help</code> n'existe pas dans un ou plusieurs cas.</p>", "sortie": ["RESULT : ", "ERREUR : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\n\npositional arguments:\n  {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n    d\u00e9poser             D\u00e9poser la quantit\u00e9 de dollars sp\u00e9cifi\u00e9e, \u00e0 la date\n                        sp\u00e9cifi\u00e9e\n    acheter             Acheter la quantit\u00e9 sp\u00e9cifi\u00e9e des titres sp\u00e9cifi\u00e9s, \u00e0\n                        la date sp\u00e9cifi\u00e9e\n    vendre              Vendre la quantit\u00e9 sp\u00e9cifi\u00e9e des titres sp\u00e9cifi\u00e9s, \u00e0\n                        la date sp\u00e9cifi\u00e9e\n    solde               Afficher en dollars le solde des liquidit\u00e9s, \u00e0 la\n                        datesp\u00e9cifi\u00e9e\n    titres              Afficher les nombres d'actions d\u00e9tenues pour chacun\n                        des titres sp\u00e9cifi\u00e9s, \u00e0 la date sp\u00e9cifi\u00e9e; affichez\n                        une ligne par titre, avec le format titre=quantit\u00e9\n    valeur              Afficher la valeur totale des titres sp\u00e9cifi\u00e9s, \u00e0 la\n                        date sp\u00e9cifi\u00e9e; affichez la valeur sur une ligne, en\n                        limitant l'affichage \u00e0 2 d\u00e9cimales\n    projection          Projeter la valeur totale des titres sp\u00e9cifi\u00e9s, \u00e0 la\n                        date future sp\u00e9cifi\u00e9e, en tenant compte des rendements\n                        et indices de volatilit\u00e9 sp\u00e9cifi\u00e9s; affichez la\n                        projection sur une seule ligne, en limitant\n                        l'affichage de la valeur \u00e0 2 d\u00e9cimales\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -q INT, --quantit\u00e9 INT\n                        Quantit\u00e9 d\u00e9sir\u00e9e (par d\u00e9faut: 1)\n  -t [STRING [STRING ...]], --titres [STRING [STRING ...]]\n                        Le ou les titres \u00e0 consid\u00e9rer (par d\u00e9faut, tous les\n                        titres du portefeuille sont consid\u00e9r\u00e9s)\n  -r FLOAT, --rendement FLOAT\n                        Rendement annuel global (par d\u00e9faut, 0)\n  -v FLOAT, --volatilit\u00e9 FLOAT\n                        Indice de volatilit\u00e9 global sur le rendement annuel\n                        (par d\u00e9faut, 0)\n  -g BOOL, --graphique BOOL\n                        Affichage graphique (par d\u00e9faut, pas d'affichage\n                        graphique)\n  -p STRING, --portefeuille STRING\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION d\u00e9poser [-h] [-q [INT]] [-d [DATE]] [-p [STRING]]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -q [INT], --quantit\u00e9 [INT]\n                        Quantit\u00e9 d\u00e9sir\u00e9e (par d\u00e9faut: 1)\n  -d [DATE], --date [DATE]\n                        Quantit\u00e9 d\u00e9sir\u00e9e (par d\u00e9faut: 1)\n  -p [STRING], --portefeuille [STRING]\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION acheter [-h] [-d [DATE]] [-q [INT]]\n                                 [-t [STRING [STRING ...]]] [-p STRING]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -q [INT], --quantit\u00e9 [INT]\n                        Quantit\u00e9 d\u00e9sir\u00e9e (par d\u00e9faut: 1)\n  -t [STRING [STRING ...]], --titres [STRING [STRING ...]]\n                        Le ou les titres \u00e0 consid\u00e9rer (par d\u00e9faut, tous les\n                        titres du portefeuille sont consid\u00e9r\u00e9s)\n  -p STRING, --portefeuille STRING\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION vendre [-h] [-t [STRING [STRING ...]]] [-q [INT]]\n                                [-d [DATE]] [-p [STRING]]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -t [STRING [STRING ...]], --titres [STRING [STRING ...]]\n                        Le ou les titres \u00e0 consid\u00e9rer (par d\u00e9faut, tous les\n                        titres du portefeuille sont consid\u00e9r\u00e9s)\n  -q [INT], --quantit\u00e9 [INT]\n                        Quantit\u00e9 d\u00e9sir\u00e9e (par d\u00e9faut: 1)\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -p [STRING], --portefeuille [STRING]\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION solde [-h] [-d [DATE]] [-p STRING] [-g [BOOL]]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -p STRING, --portefeuille STRING\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n  -g [BOOL], --graphique [BOOL]\n                        Affichage graphique (par d\u00e9faut, pas d'affichage\n                        graphique)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION titres [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -t [STRING [STRING ...]], --titres [STRING [STRING ...]]\n                        Le ou les titres \u00e0 consid\u00e9rer (par d\u00e9faut, tous les\n                        titres du portefeuille sont consid\u00e9r\u00e9s)\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -p STRING, --portefeuille STRING\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n  -g BOOL, --graphique BOOL\n                        Affichage graphique (par d\u00e9faut, pas d'affichage\n                        graphique)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION valeur [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -t [STRING [STRING ...]], --titres [STRING [STRING ...]]\n                        Le ou les titres \u00e0 consid\u00e9rer (par d\u00e9faut, tous les\n                        titres du portefeuille sont consid\u00e9r\u00e9s)\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -p STRING, --portefeuille STRING\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n  -g BOOL, --graphique BOOL\n                        Affichage graphique (par d\u00e9faut, pas d'affichage\n                        graphique)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION projection [-h] [-t [STRING [STRING ...]]]\n                                    [-d [DATE]] [-r [FLOAT]] [-v [FLOAT]]\n                                    [-p [STRING]] [-g [BOOL]]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -t [STRING [STRING ...]], --titres [STRING [STRING ...]]\n                        Le ou les titres \u00e0 consid\u00e9rer (par d\u00e9faut, tous les\n                        titres du portefeuille sont consid\u00e9r\u00e9s)\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -r [FLOAT], --rendement [FLOAT]\n                        Rendement annuel global (par d\u00e9faut, 0)\n  -v [FLOAT], --volatilit\u00e9 [FLOAT]\n                        Indice de volatilit\u00e9 global sur le rendement annuel\n                        (par d\u00e9faut, 0)\n  -p [STRING], --portefeuille [STRING]\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n  -g [BOOL], --graphique [BOOL]\n                        Affichage graphique (par d\u00e9faut, pas d'affichage\n                        graphique)\n"], "erreur": [], "mauvaisResultat": [], "note": 60, "ponderation": 60}, {"critere": "1", "command": ["d\u00e9poser", "acheter", "vendre", "solde", "titres", "valeur", "projection", "d\u00e9poser --portefeuille", "d\u00e9poser --quantit\u00e9", "d\u00e9poser --date", "d\u00e9poser -q", "d\u00e9poser -d", "d\u00e9poser -p", "acheter --portefeuille", "acheter --quantit\u00e9", "acheter --titres", "acheter --date", "acheter -q", "acheter -t", "acheter -d", "acheter -p", "vendre --portefeuille", "vendre --quantit\u00e9", "vendre --titres", "vendre --date", "vendre -q", "vendre -t", "vendre -d", "vendre -p", "solde --graphique", "solde --portefeuille", "solde --date", "solde -d", "solde -p", "solde -g", "titres --graphique", "titres --portefeuille", "titres --titres", "titres --date", "titres -t", "titres -d", "titres -p", "titres -g", "valeur --graphique", "valeur --portefeuille", "valeur --date", "valeur --titres", "valeur -t", "valeur -d", "valeur -p", "valeur -g", "projection --graphique", "projection --portefeuille", "projection --titres", "projection --date", "projection --rendement", "projection --volatilit\u00e9", "projection -t", "projection -d", "projection -r", "projection -v", "projection -p", "projection -g"], "nom": "<p><h3>Nomenclature", "erreurAttendu": ["expected one argument", "expected at least one argument"], "attendu": [], "description": "<p><strong>V\u00e9rifer la nomenclature des arguments et actions.</strong></p>", "commentaire": "<p>Des actions et/ou arguments sont mal nomm\u00e9s.</p>", "sortie": ["RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : 1 $\n", "RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : 0.0\n", "RESULT : ", "ERREUR : 0.00\n", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 17, in d\u00e9poser\n    folio = inst.d\u00e9poser(arg.quantit\u00e9, DATE)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 100, in d\u00e9poser\n    self.dico[pos[1]].append(self.dico[pos[1]][1] + montant)\nTypeError: unsupported operand type(s) for +: 'int' and 'NoneType'\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 17, in d\u00e9poser\n    folio = inst.d\u00e9poser(arg.quantit\u00e9, DATE)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 100, in d\u00e9poser\n    self.dico[pos[1]].append(self.dico[pos[1]][1] + montant)\nTypeError: unsupported operand type(s) for +: 'int' and 'NoneType'\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION acheter [-h] [-d [DATE]] [-q [INT]]\n                                 [-t [STRING [STRING ...]]] [-p STRING]\ngesport.py ACTION acheter: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION acheter [-h] [-d [DATE]] [-q [INT]]\n                                 [-t [STRING [STRING ...]]] [-p STRING]\ngesport.py ACTION acheter: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : ", "ERREUR : 1 $\n", "RESULT : usage: gesport.py ACTION solde [-h] [-d [DATE]] [-p STRING] [-g [BOOL]]\ngesport.py ACTION solde: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION solde [-h] [-d [DATE]] [-p STRING] [-g [BOOL]]\ngesport.py ACTION solde: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : ", "ERREUR : 1 $\n", "RESULT : usage: gesport.py ACTION titres [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION titres: error: argument -g/--graphique: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION titres [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION titres: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION titres [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION titres: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION titres [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION titres: error: argument -g/--graphique: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION valeur [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION valeur: error: argument -g/--graphique: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION valeur [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION valeur: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : ", "ERREUR : 0.0\n", "RESULT : ", "ERREUR : 0.0\n", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION valeur [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION valeur: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION valeur [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION valeur: error: argument -g/--graphique: expected one argument\n", "ERREUR : ", "RESULT : ", "ERREUR : 0.00\n", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : ", "ERREUR : 0.00\n", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : ", "ERREUR : 0.00\n", "RESULT : ", "ERREUR : (0.0, 0.0, 0.0)\n", "RESULT : ", "ERREUR : 0.00\n", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": [], "note": 10, "ponderation": 10}, {"critere": "1", "command": ["-v", "-d", "-q", "-t", "-g", "-r", "-p", "d\u00e9poser -v", "d\u00e9poser -t", "d\u00e9poser -g", "d\u00e9poser -r", "acheter -v", "acheter -g", "acheter -r", "vendre -v", "vendre -g", "vendre -r", "solde -v", "solde -q", "solde -t", "solde -r", "titres -v", "titres -q", "titres -r", "valeur -v", "valeur -q", "valeur -r", "projection -q"], "nom": "<p><h3>Trop d'arguments", "erreurAttendu": ["unrecognized arguments", "following arguments are required"], "attendu": [], "description": "<p>V\u00e9rifier que les actions n'ont pas d'arguments superflus.</strong></p>", "commentaire": "<p>Des actions ont des arguments superflus.</p>", "sortie": ["RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: argument -v/--volatilit\u00e9: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: argument -q/--quantit\u00e9: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\nAttributeError: 'Namespace' object has no attribute 'func'\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: argument -g/--graphique: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: argument -r/--rendement: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -v\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -t\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -g\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -r\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -v\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -g\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -r\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -v\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -g\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -r\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -v\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -q\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -t\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -r\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -v\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -q\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -r\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -v\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -q\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -r\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION [-h] [-d [DATE]] [-q INT] [-t [STRING [STRING ...]]]\n                         [-r FLOAT] [-v FLOAT] [-g BOOL] [-p STRING]\n                         {d\u00e9poser,acheter,vendre,solde,titres,valeur,projection}\n                         ...\ngesport.py ACTION: error: unrecognized arguments: -q\n", "ERREUR : "], "erreur": [], "mauvaisResultat": [], "note": 10, "ponderation": 10}, {"critere": "1", "command": ["d\u00e9poser", "acheter", "vendre", "solde", "titres", "valeur", "projection", "d\u00e9poser -q", "d\u00e9poser -d", "d\u00e9poser -p", "acheter -q", "acheter -t", "acheter -d", "acheter -p", "vendre -q", "vendre -t", "vendre -d", "vendre -p", "solde -d", "solde -p", "solde -g", "titres -t", "titres -d", "titres -p", "titres -g", "valeur -t", "valeur -d", "valeur -p", "valeur -g", "projection -t", "projection -d", "projection -r", "projection -v", "projection -p", "projection -g"], "nom": "<p><h3>Manque d'argument", "erreurAttendu": ["expected one argument", "expected at least one argument"], "attendu": [], "description": "<p><strong>V\u00e9rifier que les actions n'ont pas d'arguments manquants.</strong></p>", "commentaire": "<p>Des actions ont des arguments manquants.</p>", "sortie": ["RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 23, in acheter\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 23, in acheter\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 23, in acheter\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION acheter [-h] [-d [DATE]] [-q [INT]]\n                                 [-t [STRING [STRING ...]]] [-p STRING]\ngesport.py ACTION acheter: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION solde [-h] [-d [DATE]] [-p STRING] [-g [BOOL]]\ngesport.py ACTION solde: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION titres [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION titres: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION titres [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION titres: error: argument -g/--graphique: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION valeur [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION valeur: error: argument -p/--portefeuille: expected one argument\n", "ERREUR : ", "RESULT : usage: gesport.py ACTION valeur [-h] [-t [STRING [STRING ...]]] [-d [DATE]]\n                                [-p STRING] [-g BOOL]\ngesport.py ACTION valeur: error: argument -g/--graphique: expected one argument\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 266, in <module>\n    DATE = dt.datetime.date(dt.datetime.strptime(ARGU.date, '%Y-%m-%d'))\nTypeError: strptime() argument 1 must be str, not None\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 53, in __init__\n    with open(nom, 'r') as fich:\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 94, in projection\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": [], "note": 10, "ponderation": 10}, {"critere": "1", "command": ["d\u00e9poser -h", "projection -h"], "nom": "<h3>Metavar", "erreurAttendu": [], "attendu": [], "description": "<p><strong>V\u00e9rifier que les arguments ont le bon metavar.</p>", "commentaire": "<p>Des arguments n'ont pas le bon <code>metavar</code>.</p>", "sortie": ["RESULT : ", "ERREUR : usage: gesport.py ACTION d\u00e9poser [-h] [-q [INT]] [-d [DATE]] [-p [STRING]]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -q [INT], --quantit\u00e9 [INT]\n                        Quantit\u00e9 d\u00e9sir\u00e9e (par d\u00e9faut: 1)\n  -d [DATE], --date [DATE]\n                        Quantit\u00e9 d\u00e9sir\u00e9e (par d\u00e9faut: 1)\n  -p [STRING], --portefeuille [STRING]\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n", "RESULT : ", "ERREUR : usage: gesport.py ACTION projection [-h] [-t [STRING [STRING ...]]]\n                                    [-d [DATE]] [-r [FLOAT]] [-v [FLOAT]]\n                                    [-p [STRING]] [-g [BOOL]]\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -t [STRING [STRING ...]], --titres [STRING [STRING ...]]\n                        Le ou les titres \u00e0 consid\u00e9rer (par d\u00e9faut, tous les\n                        titres du portefeuille sont consid\u00e9r\u00e9s)\n  -d [DATE], --date [DATE]\n                        Date effective (par d\u00e9faut, date du jour)\n  -r [FLOAT], --rendement [FLOAT]\n                        Rendement annuel global (par d\u00e9faut, 0)\n  -v [FLOAT], --volatilit\u00e9 [FLOAT]\n                        Indice de volatilit\u00e9 global sur le rendement annuel\n                        (par d\u00e9faut, 0)\n  -p [STRING], --portefeuille [STRING]\n                        Nom de portefeuille (par d\u00e9faut, utiliser folio)\n  -g [BOOL], --graphique [BOOL]\n                        Affichage graphique (par d\u00e9faut, pas d'affichage\n                        graphique)\n"], "erreur": [], "mauvaisResultat": [], "note": 10, "ponderation": 10}, {"critere": "2", "command": ["d\u00e9poser -q 1000000000 -d 2018-09-17 -p PF1", "d\u00e9poser -q 10000 -d 2018-09-17", "d\u00e9poser -d 2018-09-17 -p PF0", "d\u00e9poser -q 10000 -p PF2"], "nom": "<p><h3>D\u00e9poser", "erreurAttendu": [], "attendu": [], "description": "<p><strong>V\u00e9rifier l'action <code>d\u00e9poser</code>.</strong></p>", "commentaire": "<p>L'action <code>d\u00e9poser</code> n'a pas le comportement attendu.</p>", "sortie": ["RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 16, in d\u00e9poser\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": [], "note": 16, "ponderation": 16}, {"critere": "2", "command": ["acheter -q 10000 -t goog -d 2018-09-17 -p PF1", "acheter -q 5 -t goog -d 2018-09-17", "acheter -t goog -d 2018-09-17 -p PF0", "acheter -q 5 -t goog -p PF2"], "nom": "<p><h3>Acheter", "erreurAttendu": ["Liquidit\u00e9Insuffisante"], "attendu": [], "description": "<p><strong>V\u00e9rifier l'action <code>acheter</code>.</strong></p>", "commentaire": "<p>L'action <code>acheter</code> n'a pas le comportement attendu.</p>", "sortie": ["RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 23, in acheter\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 23, in acheter\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Votre programme a mis plus que 1s \u00e0 s'executer", "ERREUR : []", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 23, in acheter\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": [], "note": 16, "ponderation": 16}, {"critere": "2", "command": ["vendre -q 500 -t goog -d 2018-09-17 -p PF1", "vendre -q 2 -t goog -d 2018-09-17", "vendre -q 500 -d 2018-09-17 -p PF1", "vendre -t goog -d 2018-09-17 -p PF0", "vendre -q 2 -t goog -p PF2"], "nom": "<p><h3>Vendre", "erreurAttendu": ["ErreurQuantit\u00e9"], "attendu": [], "description": "<p><strong>V\u00e9rifier l'action <code>vendre</code>.</strong></p>", "commentaire": "<p>L'action <code>vendre</code> n'a pas le comportement attendu.</p>", "sortie": ["RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Votre programme a mis plus que 1s \u00e0 s'executer", "ERREUR : []", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 33, in vendre\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": [], "note": 20, "ponderation": 20}, {"critere": "2", "command": ["solde -d 2018-09-17 -p PF1", "solde -d 2018-09-17", "solde -p PF0", "solde -p PF2"], "nom": "<p><h3>Solde", "erreurAttendu": [], "attendu": ["989595550.00", "6531.85", "1.00", "6971.77"], "description": "<p><strong>V\u00e9rifier l'action <code>solde</code>.</strong></p>", "commentaire": "<p>L'action <code>solde</code> n'a pas le comportement attendu.</p>", "sortie": ["RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : ", "ERREUR : 1 $\n", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": ["<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'solde', '-d', '2018-09-17', '-p', 'PF1']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>", "<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'solde', '-d', '2018-09-17']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>", "<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'solde', '-p', 'PF2']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 44, in solde\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>"], "note": 16, "ponderation": 16}, {"critere": "2", "command": ["titres -t goog -d 2018-09-17 -p PF1", "titres -t goog -d 2018-09-17", "titres -d 2018-09-17 -p PF0", "titres -t goog -p PF2"], "nom": "<p><h3>Titres", "erreurAttendu": [], "attendu": ["[G|g][O|o][O|o][G|g]=9000", "[G|g][O|o][O|o][G|g]=3", "[G|g][O|o][O|o][G|g]=3", "[G|g][O|o][O|o][G|g]=3"], "description": "<p><strong>V\u00e9rifier l'action <code>titres</code>.</strong></p>", "commentaire": "<p>L'action <code>titres</code> n'a pas le comportement attendu.</p>", "sortie": ["RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : ", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": ["<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'titres', '-t', 'goog', '-d', '2018-09-17', '-p', 'PF1']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>", "<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'titres', '-t', 'goog', '-d', '2018-09-17']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>", "<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'titres', '-t', 'goog', '-p', 'PF2']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 54, in titres\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>"], "note": 16, "ponderation": 16}, {"critere": "2", "command": ["valeur -t goog -d 2018-09-17 -p PF1", "valeur -t goog -d 2018-09-17", "valeur -t goog -p PF0", "valeur -d 2018-09-17 -p PF2"], "nom": "<p><h3>Valeur", "erreurAttendu": [], "attendu": ["10404450.00", "3468.15", "0.00", "0.00"], "description": "<p><strong>V\u00e9rifier l'action <code>valeur</code>.</strong></p>", "commentaire": "<p>L'action <code>valeur</code> n'a pas le comportement attendu.</p>", "sortie": ["RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : ", "RESULT : ", "ERREUR : 0.0\n", "RESULT : Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n", "ERREUR : "], "erreur": [], "mauvaisResultat": ["<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'valeur', '-t', 'goog', '-d', '2018-09-17', '-p', 'PF1']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>", "<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'valeur', '-t', 'goog', '-d', '2018-09-17']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>", "<li><p>Dans le contexte suivant :</p><pre class=\"line-numbers  language-python\"><code>['python3.7', '../unbundled/bundle-027-04.hg/gesport.py', 'valeur', '-d', '2018-09-17', '-p', 'PF2']</code></pre><p>Votre code ne soul\u00e8ve pas d'erreur mais ceci n'\u00e9tait pas le r\u00e9sultat attendu :<p><pre class=\"line-numbers  language-python\"><code>Traceback (most recent call last):\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 267, in <module>\n    ARGU.func(ARGU)\n  File \"../unbundled/bundle-027-04.hg/gesport.py\", line 69, in valeur\n    inst = pt.Portefeuille(arg.portefeuille)\n  File \"/mnt/Documents/Projets/Laval/TA/TP3/unbundled/bundle-027-04.hg/portefeuille.py\", line 54, in __init__\n    chaine = json.loads(fich.read())\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte\n</code></pre></li>"], "note": 16, "ponderation": 16}]